"""add course_name to enrollments

Revision ID: 12aef4ff4368
Revises: 7b4aa852b80c
Create Date: 2021-05-14 12:54:44.110236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12aef4ff4368'
down_revision = '7b4aa852b80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('course_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment', 'course_name')
    # ### end Alembic commands ###
