"""update course table

Revision ID: 1358ad741915
Revises: 2c8fa162f9f7
Create Date: 2021-05-11 15:47:41.090608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1358ad741915'
down_revision = '2c8fa162f9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('content_url', sa.String(length=128), nullable=True),
    sa.Column('assessment_file', sa.String(length=128), nullable=True),
    sa.Column('youtube_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=True)
    op.drop_index('ix_courses_name', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('content_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('assessment_file', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_name', 'courses', ['name'], unique=False)
    op.drop_index(op.f('ix_course_name'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
